# back_end/python_scripts/magnus_slurm.py
import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path

def log_cloud_only(msg: str):
    """
    辅助函数：只打印到标准输出（给 Magnus 云端看），不写入用户本地文件。
    """
    sys.stdout.write(f"{msg}\n")
    sys.stdout.flush()

def main():
    parser = argparse.ArgumentParser(description="Magnus SLURM Proxy Executor")
    parser.add_argument("--working-directory", required=True, help="Job working directory")
    parser.add_argument("--slurm-script", required=True, help="Content of the shell script to run")
    parser.add_argument("--conda-environment", required=True, help="Conda environment to activate")
    parser.add_argument("--output-path", default="", help="Optional path to redirect stdout/stderr")
    
    args = parser.parse_args()

    # 1. 准备工作目录
    work_dir = Path(args.working_directory).expanduser().resolve()
    log_cloud_only(f"[Magnus] Setting up working directory: {work_dir}")
    os.makedirs(work_dir, exist_ok=True)

    # 2. 生成临时包装脚本
    # 这一步只负责生成纯粹的执行逻辑，不要在此处打印任何 [Magnus] 相关的日志
    temp_script = tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.sh', prefix='magnus_runner_')
    script_path = Path(temp_script.name)
    
    try:
        wrapper_content = f"""#!/bin/bash
# --- Auto-generated by Magnus Platform ---

# A. Initialize Conda
if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
    source "$HOME/miniconda3/etc/profile.d/conda.sh"
elif [ -f "/opt/miniconda3/etc/profile.d/conda.sh" ]; then
    source "/opt/miniconda3/etc/profile.d/conda.sh"
elif [ -f "$HOME/anaconda3/etc/profile.d/conda.sh" ]; then
    source "$HOME/anaconda3/etc/profile.d/conda.sh"
else
    CONDA_BASE=$(conda info --base 2>/dev/null)
    if [ -n "$CONDA_BASE" ]; then
        source "$CONDA_BASE/etc/profile.d/conda.sh"
    fi
fi

# B. Activate Environment
# 如果激活失败，直接报错退出。不需要 echo [Magnus] ...
conda activate {args.conda_environment} || {{ echo "Error: Failed to activate environment '{args.conda_environment}'"; exit 1; }}

# C. Execute User Script
set -e
{args.slurm_script}
"""
        temp_script.write(wrapper_content)
        temp_script.close()
        script_path.chmod(0o755)

        # 3. 确定本地日志路径
        if args.output_path:
            out_path = Path(args.output_path).expanduser()
            if not out_path.is_absolute():
                out_path = work_dir / out_path
        else:
            job_id = os.environ.get("SLURM_JOB_ID", "local")
            out_path = work_dir / f"slurm-{job_id}.out"

        out_path.parent.mkdir(parents=True, exist_ok=True)
        
        # --- Python 层打印控制信息 ---
        log_cloud_only(f"[Magnus] Activating Conda environment: {args.conda_environment}")
        log_cloud_only(f"[Magnus] Redirecting user output to: {out_path}")
        
        # --- 打印分隔符 (云端可见，不进文件) ---
        log_cloud_only("-" * 60)
        log_cloud_only(">>> User Script Execution Start >>>")
        log_cloud_only("-" * 60)

        # 4. 执行脚本 (直通模式)
        cmd = ["bash", str(script_path)]
        
        # 打开文件准备写入
        with open(out_path, "w", encoding="utf-8") as outfile:
            process = subprocess.Popen(
                cmd, 
                cwd=work_dir, 
                stdout=subprocess.PIPE, 
                stderr=subprocess.STDOUT, # 将用户的 stderr 合并进 stdout
                text=True, 
                bufsize=1 # 行缓冲
            )
            
            assert process.stdout is not None
            
            # === 核心逻辑：无过滤直通 ===
            # 现在非常干净：管道里出来的全是用户脚本(或conda报错)的真实输出
            # 我们不需要检查 startswith，直接两头写
            for line in process.stdout:
                # 1. 写入本地文件
                outfile.write(line)
                outfile.flush()
                
                # 2. 打印到云端流
                sys.stdout.write(line)
                sys.stdout.flush() 

            return_code = process.wait()

        # --- 打印结束分隔符 ---
        log_cloud_only("-" * 60)
        log_cloud_only(f"<<< User Script Execution End (Exit Code: {return_code}) <<<")
        log_cloud_only("-" * 60)

        # 5. 检查结果
        if return_code != 0:
            log_cloud_only(f"[Magnus] Job failed.")
            sys.exit(return_code)
        
        log_cloud_only(f"[Magnus] Job completed successfully.")

    except Exception as e:
        log_cloud_only(f"[Magnus] Critical Error: {str(e)}")
        sys.exit(1)
        
    finally:
        # 6. 清理
        if script_path.exists():
            try:
                os.remove(script_path)
            except OSError:
                pass

if __name__ == "__main__":
    main()